adminpanel/urls.py
from django.urls import path, include

from .views import (CustomerDetailView, CustomerEditView, CustomerManagementView, DashboardView,
                    ForgotPasswordView, LoginView, LogoutView, NotificationsView, PasswordResetConfirmationView, PasswordResetView, SettingsView,
                    StaticContentManagementView,InvestingReportView, StockEditView, StockManagementView, StockUploadTemplateView, StockUploadView,SubscriptionManagementView, TipAddView, TipEditView, TipManagementView)

app_name = "adminpanel"
urlpatterns = [
    path("", DashboardView.as_view(), name="base"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("forgot-password/", ForgotPasswordView.as_view(), name="forgot-password"),
    path("password-reset-confirmation/", PasswordResetConfirmationView.as_view(), name="password-reset-confirmation"),
    path("password-reset/", PasswordResetView.as_view(),name="password-reset"),
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
    path("customer-management/", CustomerManagementView.as_view(), name="customer-management"),
    path("customer-detail/<int:pk>/", CustomerDetailView.as_view(), name="customer-detail"),
    path("customer-edit/<int:pk>/", CustomerEditView.as_view(), name="customer-edit"),
    path("investing-reports/", InvestingReportView.as_view(), name="investing-reports"),
    path("subscription-management/", SubscriptionManagementView.as_view(), name="subscription-management"),
    path("stock-upload/", StockUploadView.as_view(), name="stock-upload"),
    path("stock-upload-template/", StockUploadTemplateView.as_view(), name="stock-upload-template"),
    path("stock-management/", StockManagementView.as_view(), name="stock-management"),
    path("stock-edit/<int:pk>/", StockEditView.as_view(), name="stock-edit"),
    path("static-content-management/", StaticContentManagementView.as_view(), name="static-content-management"),
    path("settings/", SettingsView.as_view(), name="settings"),
    path("tip-management/", TipManagementView.as_view(), name="tip-management"),
    path("tip-add/", TipAddView.as_view(), name="tip-add"),
    path("tip-edit/<int:pk>/", TipEditView.as_view(), name="tip-edit"),

    path("notifications/", NotificationsView.as_view(), name="notifications"),

    path('quizzes/', include("quizzes.urls", namespace="quizzes")),
    path('wallets/', include("wallets.urls", namespace="wallets")),
]

api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from api.views import (
    AboutUsViewSet,
    BasicUserViewSet,
    CheckOldPassword,
    ContactDataViewSet,
    FAQViewSet,
    GetFundsViewSet,
    InvestmentInsightViewSet,
    JournalViewSet,
    LoginView,
    LogoutView,
    MarketFilterViewSet,
    NotificationViewSet,
    PortFolioView,
    PrivacyPolicyViewSet,
    RegisterView,
    ResetPasswordView,
    SendVerififcationEmailView,
    SubscriptionHistoryViewSet,
    SubscriptionViewSet,
    TermsNConditionsViewSet,
    TipViewSet,
    TradeViewSet,
    TransactionLatestView,
    TransactionViewSet,
    UserProfilePhotoViewSet,
    UserProfileViewSet,
    UserSettingViewSet,
    CheckEmailPhonePanNumber,
    InvestmentInsightViewSet,
    VerifyEmailView,
    QuizViewSet, QuizEnrollmentViewSet, WalletViewSet
)
from api.zerodha_urls import urlpatterns as zerodha_urls
from payment.views import SubscribeView
from quizzes.views import QuizViewAPI, QuizEnrollmentAPI, QuizAnswerAPI
from wallets.views import WalletViewAPI

app_name = "api"

router = DefaultRouter()

router.register(r"profile", UserProfileViewSet, basename="profile")
router.register(r"profile/user-data", BasicUserViewSet, basename="user-data")
router.register(r"profile/profile-photo", UserProfilePhotoViewSet, basename="profile-photo")
router.register(r"settings", UserSettingViewSet, basename="settings")
router.register(r"notifications", NotificationViewSet, basename="notifications")

router.register(r"market/filter", MarketFilterViewSet, basename="market-filter")

router.register(r"funds", GetFundsViewSet, basename="get-funds")

#Transactions
router.register(r"investment-insight/insights", InvestmentInsightViewSet,basename="investment-insight")
router.register(r"investment-insight/transactions", TransactionViewSet, basename="transaction")
router.register(r"trade", TradeViewSet, basename="trade")
router.register(r"journal", JournalViewSet, basename="journal")

#Subscriptions
# router.register(r"subscription/subscribe",SubscribeViewSet,basename="subscribe")
router.register(r"subscription/detail", SubscriptionViewSet,basename="subscription-detail")
router.register(r"subscription/history", SubscriptionHistoryViewSet,basename="subscription-history")

#Static
router.register(r"static/about-us", AboutUsViewSet, basename="about-us")
router.register(r"static/privacy-policy", PrivacyPolicyViewSet, basename="privacy-policy")
router.register(r"static/terms-n-conditions", TermsNConditionsViewSet, basename="terms-n-conditions")
router.register(r"static/contact-details", ContactDataViewSet, basename="contact-details")
router.register(r"static/faqs", FAQViewSet, basename="faqs")
router.register(r"static/tip", TipViewSet, basename="tips")

# Quizzes
router.register(r"quizzes", QuizViewSet, basename="quizzes")
# router.register(r"quizzes/enrollment", QuizEnrollmentViewSet, basename="quizzes")

# Wallets
router.register(r"wallets", WalletViewSet, basename="quizzes")


urlpatterns = [
    # Direct urls
    path("auth/reset-password/", ResetPasswordView.as_view(), name="reset-password"),
    path("auth/register/", RegisterView.as_view(), name="register"),
    path("auth/login/", LoginView.as_view(), name="login"),
    path("auth/logout/", LogoutView.as_view(), name="logout"),
    path("check/email-phone-pan/", CheckEmailPhonePanNumber.as_view(), name="check-email-phone-pan"),
    path("check/old-password/", CheckOldPassword.as_view(), name="check-old-password"),
    path("portfolio/", PortFolioView.as_view(), name="portfolio"),
    path("investment-insight/transactions/latest/", TransactionLatestView.as_view(), name="transaction-latest"),
    path("verify/send-verification-email/", SendVerififcationEmailView.as_view(), name="send-verification-email"),
    path("verify/email/", VerifyEmailView.as_view(), name="email-verification"),
    path("subscription/subscribe/", SubscribeView.as_view(), name="subscribe"),

    # Quizzes
    path("quizzes/", QuizViewAPI.as_view(), name="quizzes"),
    path("quizzes/enroll", QuizEnrollmentAPI.as_view(), name="quiz-enrollment"),
    path("quizzes/<int:pk>/answers", QuizAnswerAPI.as_view(), name="quiz-answers"),

    # Wallets
    path("wallets/", WalletViewAPI.as_view(), name="wallet"),
    # Routers
    path("", include(router.urls)),
    path("zerodha/", include(zerodha_urls)),
]

invest/urls.py
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

from adminpanel.views import DashboardView

urlpatterns = [
    path("adminpanel/", include("adminpanel.urls", namespace="adminpanel")),
    path("", DashboardView.as_view(), name="dashboard"),
    path('api/', include("api.urls", namespace="api")),
    path('payments/', include("payment.urls", namespace="payment")),

    #Schema/Docs
    path('schema/', SpectacularAPIView.as_view(), name='schema'),
    path('docs/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/customer_edit.html
{% extends "logged_in_base.html" %}
{% block title %}Customer Edit{% endblock %}
{% block content %}
    <div class="WrapperArea">
        <div class="WrapperBox">
            <div class="TitleBox">
                <h4>Edit Customer </h4>
                <div class="BackPage">
                    <a href={% url "adminpanel:customer-management" %}><i class="fa fa-long-arrow-left" aria-hidden="true"></i>Back</a>
                </div>
            </div>
            <div class="InnerBox">
                <form action={% url "adminpanel:customer-edit" user.id%} method="POST">
                    {% csrf_token %}
                <div class="CommonForm">
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label>First  Name</label>
                                <input type="text" class="form-control" placeholder="First Name" value = "{{user.profile.first_name}}" name="first_name">
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label>Last Name</label>
                                <input type="text" class="form-control" placeholder="Last Name" value = "{{user.profile.last_name}}" name="last_name">
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label>Email Address</label>
                                <input type="email" class="form-control" placeholder="Enter Email Address" value = "{{user.email}}" name="email" readonly>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label>Mobile Number</label>
                                <input type="text" maxlength="10" minlength="10" title="Phone number must be of length 10" pattern="[0-9]{10}" class="form-control" placeholder="Enter Mobile Number" value = "{{user.phone_number}}" name="phone_number" readonly>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label>PAN  Number</label>
                                <input type="text" pattern="[A-Z]{5}[0-9]{4}[A-Z]{1}" title="Pancard must follow 'AAAAA0000A' pattern" class="form-control" placeholder=" Enter PAN  Number" value = "{{user.profile.pan_number}}" name="pan_number" readonly>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label>Date of Birth</label>
                                <input type="date" class="form-control" placeholder=" Enter Date of Birth" value = "{{user.profile.date_of_birth|date:"Y-m-d"}}" name="date_of_birth" readonly>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label>Gender</label>
                                <select class="form-control" style="pointer-events: none;" onclick="return false;" onkeydown="return false;" name="gender" readonly>
                                    <option {% if user.profile.gender == "Male"%} selected {% endif %}>Male</option>
                                    <option {% if user.profile.gender == "Female"%} selected {% endif %}>Female</option>
                                    <option {% if user.profile.gender == "Other"%} selected {% endif %}>Others</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label>Address</label>
                                <textarea rows="5" class="form-control" name="address">{{user.profile.address}}</textarea>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="ButtonMain">
                    <button href="javascript:void(0); " class="Button">Update Customer</button>
                </div>
            </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/logged_in_base.html
{% extends "base.html" %}
{% block body %}
    <div class="Header">
        <div class="Logo">
            <img src="/media/images/inner-logo.png">
        </div>
        <div class="Navigation">
            <a href={% url "adminpanel:notifications" %} class="Notification"><i class="fa fa-bell" aria-hidden="true"></i></a>
            <div class="Avater">
                <a href="javascript:void(0);">
                    <figure>
                        <img src="/media/images/user5.jpg">
                    </figure>
                    Anuradha
                </a>
                <ul>
                    <li>
                        <figure>
                            <img src="/media/images/user5.jpg">
                        </figure>
                        <h4>
                            Anuradha <span>Administrator</span>
                        </h4>
                    </li>
                    <li>
                        <a href={% url "adminpanel:settings" %}><span><i class="fa fa-cogs" aria-hidden="true"></i></span> Settings</a>
                    </li>
                    <li>
                        <a href={% url "adminpanel:logout" %}><span><i class="fa fa-sign-out"></i></span> Logout</a>
                    </li>
                </ul>
            </div>
            <div class="clear"></div>
        </div>
    </div>
    <div class="SidenavBar">
        <div class="Logo">
            <img src="/media/images/inner-logo.png">
        </div>
        <ul>
            <li>
                <a href={% url "adminpanel:dashboard" %}>
                    <span><i class="fa fa-tachometer" aria-hidden="true"></i></span> Dashboard
                </a>
            </li>
            <li>
                <a href={% url "adminpanel:customer-management" %}>
                    <span><i class="fa fa-users" aria-hidden="true"></i></span> Customer Management
                </a>
            </li>
            <li>
                <a href={% url "adminpanel:investing-reports" %}>
                    <span><i class="fa fa-money" aria-hidden="true"></i></span> Investing Reports
                </a>
            </li>
            <li>
                <a href={% url "adminpanel:subscription-management" %}>
                    <span><i class="fa fa-inr" aria-hidden="true"></i></span> Subscription Management
                </a>
            </li>
            <li>
                <a href={% url "adminpanel:stock-management" %}>
                    <span><i class="fa fa-cubes" aria-hidden="true"></i></span> Stock Management
                </a>
            </li>
            <li>
                <a href={% url "adminpanel:static-content-management" %}>
                    <span><i class="fa fa-font"></i></span> Content Management
                </a>
            </li>
            <li>
                <a href={% url "adminpanel:quizzes:list-quizzes" %}>
                    <span><i class="fa fa-quora"></i></span> Quiz Management
                </a>
            </li>
            <li>
                <a href={% url "adminpanel:tip-management" %}>
                    <span><i class="fa fa-lightbulb-o" aria-hidden="true"></i></span> Tip Management
                </a>
            </li>
            <li>
                <a href={% url "adminpanel:settings" %}>
                    <span><i class="fa fa-cogs" aria-hidden="true"></i></span> Settings
                </a>
            </li>
            <li>
                <a href={% url "adminpanel:logout" %}>
                    <span><i class="fa fa-sign-out"></i></span> Logout
                </a>
            </li>
        </ul>
    </div>
    {% block content %}{% endblock content %}
    <script>
        document.querySelector(`[href='${window.location.pathname}']`).parentElement.classList.add("active");
    </script>
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block body %}
<div class="LoginPage">
    <div class="LoginBox">
        <div class="row">
            <div class="col-sm-6 ">
            <div class="loginLeft">
                <figure>
                    <img src="/media/images/Login2.png">
                </figure>
                <p>To stay connected with us, please log in.</p>
            </div>
            </div>
            <div class="col-sm-6">
                <div class="RightLogin">
                    <div class="MainRight">
                        <a href="/">
                            <figure>
                                <img src="/media/images/logo2.png">
                            </figure>
                        </a>
                        <h3>Let's Start Investing. </h3>
                        {% include "fragments/messages.html"%}
                        <form action="{% url 'adminpanel:login' %}" method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                                <label>Email ID</label>
                                <input type="text" name="email" placeholder="Enter Email ID" class="form-control">
                                <span class="Icon"><i class="fa fa-envelope"></i></span>
                            </div>
            
                            <div class="form-group">
                                <label>Password </label>
                                <input type="password" name="password" placeholder="Enter Password" class="form-control">
                                <span class="Icon"><i class="fa fa-unlock-alt"></i></span>
                            </div>
            
                            <div class="Checkboxs">
                                <a href="{% url 'adminpanel:forgot-password' %}">Forgot password?</a>
                            </div>
                            <button type="submit" class="Button">Log In <i class="fa fa-sign-in"></i></button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/messages.html
{% if messages %}
    {% for message in messages %}
    <div {% if message.tags %} class="{{ message.tags }} alert-dismissible" id="" role="alert" {% endif %}>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true"> &times; </span></button>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %} {% endif %}
        {{ message }}
    </div>
    {% endfor %}
{% endif %}

templates/stock_edit.html
{% extends "logged_in_base.html" %}
{% block title %}Stock Edit{% endblock %}
{% block content %}
    <div class="WrapperArea">
        <div class="WrapperBox">
            <div class="TitleBox">
                <h4>Edit Stock </h4>
                <div class="BackPage">
                    <a href={% url "adminpanel:stock-management" %}><i class="fa fa-long-arrow-left" aria-hidden="true"></i>Back</a>
                </div>
            </div>
            <div class="InnerBox">
                <form action={% url "adminpanel:stock-edit" stock.id%} method="POST">
                    {% csrf_token %}
                <div class="CommonForm">
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label>Company Name</label>
                                <input type="text" class="form-control" placeholder="First Name" value = "{{stock.company_name}}" name="company_name" required>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label>Symbol</label>
                                <input type="text" class="form-control" placeholder="Last Name" value = "{{stock.symbol}}" name="symbol" readonly>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label>Series</label>
                                <input type="text" class="form-control" placeholder="First Name" value = "{{stock.series}}" name="series">
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label>Extra Text</label>
                                <input type="text" class="form-control" placeholder="Last Name" value = "{{stock.extra_text}}" name="extra_text">
                            </div>
                        </div>
                        <div class="ButtonMain" style="margin:auto;">
                            <button class="Button">Update Stock</button>
                        </div>
            </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/tip_edit.html
{% extends "logged_in_base.html" %}
{% block title %}Edit Tip{% endblock %}
{% block content %}
    <div class="WrapperArea">
        <div class="WrapperBox">
            <div class="TitleBox">
                <h4>Update your tip</h4>
                <div class="BackPage">
                    <a href={% url "adminpanel:tip-management" %}><i class="fa fa-long-arrow-left" aria-hidden="true"></i>Back</a>
                </div>
            </div>
            <form action={% url "adminpanel:tip-edit" tip.id %} method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <textarea rows="10" name="tip_text" class="form-control" id="tip_text" spellcheck="false" required>{{tip.text}}</textarea>
                    <div class="Save">
                        <button class="Button" type="submit">Save</button>
                    </div>
                </div>
            </form>
            {% include "fragments/messages.html" %}
        </div>
    </div>
    <script>
{% endblock %}

templates/tip_management.html
{% extends "logged_in_base.html" %}
{% block title %}Tips Management{% endblock %}
{% block content %}
    <div class="WrapperArea">
        <div class="WrapperBox">
            <div class="TitleBox">
                <h4>Tips Management</h4>
                <a class="Button"
                   href="{% url 'adminpanel:tip-add' %}"
                   style="width:revert">
                    <i class="fa fa-plus"></i> Add Tip
                </a>
            </div>
            {% include "fragments/messages.html" %}
            <div class="InnerBox">
                <div class="FlexMain">
                    <div class="Search">
                        <form action={% url "adminpanel:tip-management" %} method="GET">
                            <input type="text" placeholder="Enter tip text" id="search_value" name="q" style="min-width:400px" {% if q %} value={{ q }}{% endif %}>
                            <button id="search" type="submit">Search</button>
                            <button class="Reset"
                                    onclick="document.querySelector('#search_value').value=''">
                                <i class="fa fa-refresh"></i>
                            </button>
                        </form>
                    </div>
                </div>
                <div class="TableList">
                    <table style="width: 100%;">
                        <thead>
                            <tr>
                                <th>Tip ID</th>
                                <th>Text</th>
                                <th>Created</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for tip in tip_list %}
                                <tr>
                                    <td class="tip_id">TIP-{{ tip.id }}</td>
                                    <td style="text-align:left; max-width:400px">{{ tip.text }}</td>
                                    <td>{{ tip.created_at }}</td>
                                    <td>
                                        <a class="Blue" href="{% url "adminpanel:tip-edit" tip.id %}">
                                            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                                        </a>
                                        <a class="Blue Delete"
                                           href="javascript:void(0)"
                                           data-toggle="modal"
                                           data-target="#Delete">
                                            <i class="fa fa-trash-o" aria-hidden="true"></i>
                                        </a>
                                        <label class="Switch">
                                            <input type="checkbox"
                                                   name="activator"
                                                   value="{{ tip.id }}"
                                                   {% if tip.is_active %}checked{% endif %}>
                                            <span class="slider"></span>
                                        </label>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% if is_paginated %}
                    <div class="Pagination">
                        <ul>
                            <li>
                                <a href="?page=1"><i class="fa fa-angle-double-left"></i></a>
                            </li>
                            {% if page_obj.has_previous %}
                                <li>
                                    <a href="?page={{ page_obj.previous_page_number }}"><i class="fa fa-angle-left"></i></a>
                                </li>
                            {% endif %}
                            {% for n in page_obj.paginator.page_range %}
                                {% if page_obj.number == n %}
                                    <li class="page-item active">
                                        <li class="active">
                                            <a href="javascript:void(0);">{{n}}</a>
                                        </li>
                                    </li>
                                {% elif n > page_obj.number|add:'-3' and n < page_obj.number|add:'3' %}
                                    <li>
                                        <a href="?page={{ n }}">{{ n }}</a>
                                    </li>
                                {% endif %}
                            {% endfor %}
                            {% if page_obj.has_next %}
                                <li>
                                    <a href="?page={{ page_obj.next_page_number }}"><i class="fa fa-angle-right"></i></a>
                                </li>
                            {% endif %}
                            <li>
                                <a href="?page={{ page_obj.paginator.num_pages }}"><i class="fa fa-angle-double-right"></i></a>
                            </li>
                        </ul>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="ModalBox">
        <div id="Delete"
             class="modal fade in"
             style="display: none;"
             aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-body">
                        <div class="Decline">
                            <a href="javascript:void(0);" class="CloseModal" data-dismiss="modal">×</a>
                            <h3>Delete</h3>
                            <p>Are you sure you want to Delete this Tip ?</p>
                            <h4>
                                <a href="javascript:void(0);" data-dismiss="modal">no</a>
                                <a href="javascript:void(0);" data-dismiss="modal" class="yesBoss">Yes</a>
                            </h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        let selected_id = null;
        let todo = "";
    </script>
    <script type="text/javascript">
        $(".Delete").on("click", function(e){
            todo = "delete"
            selected_id =e.target.closest("tr").querySelector(".tip_id").textContent.replace("TIP-","")
        })

        $(".yesBoss").on("click",function(e){
            modifyUser()
        })
    </script>
    <script>
        function updateSelectedUserId(element){
            selected_id = element.closest("tr").querySelector(".tip_id").textContent.replace("TIP-","")
        }
        function modifyUser(){
            let url = "{% url 'adminpanel:tip-management' %}"
            $.ajaxSetup({
                headers: {
                    "X-CSRFToken": '{{csrf_token}}'
                }
            });
            $.ajax({
                url: url,
                method: 'POST',
                data: {
                    "todo": todo,
                    "selected_id": selected_id 
                }
            });
            if(todo=="delete"){
                setTimeout(reload, 2000);
            }
        }

        function reload() {
            document.location.reload();
          }
    </script>
    <script>
        $('.Switch input[type="checkbox"]').on("change", function (e) {
            toggler = e.target;
            if (e.target.checked == true) {
                todo = "activate";
                updateSelectedUserId(e.target);
                modifyUser();
                checkboxes = document.querySelectorAll('.Switch input[type="checkbox"]')
                for(i=0;i<checkboxes.length;i++){
                    if (checkboxes[i]!=e.target){
                        checkboxes[i].checked = false;
                    }
                }
            } else {
                Eggy({
                    title: 'Error!',
                    message: 'Cannot decativate an active tip, please activate anothe tip.',
                    type: 'error',
                    duration: 4000
                })
                e.target.checked = true;
            }
        });
    </script>
{% endblock %}